import { z } from "zod"; import { fetchWithPolicy } from "@/lib/http"; import type { MarketMetrics,MarketPeriod,PoolAnalysis } from "@/lib/types";
const numeric=z.union([z.string(),z.number()]).nullish().transform(v=>v==null?null:Number(v));
const period=z.object({m5:numeric,h1:numeric,h6:numeric,h24:numeric}).partial().nullish();
const tx=z.object({buys:z.number().nullish(),sells:z.number().nullish()});
const pair=z.object({chainId:z.string(),dexId:z.string(),pairAddress:z.string(),baseToken:z.object({address:z.string(),symbol:z.string()}),quoteToken:z.object({address:z.string(),symbol:z.string()}),priceUsd:numeric,priceNative:numeric,liquidity:z.object({usd:numeric}).nullish(),fdv:numeric,marketCap:numeric,pairCreatedAt:numeric,volume:period,priceChange:period,txns:z.object({m5:tx.nullish(),h1:tx.nullish(),h6:tx.nullish(),h24:tx.nullish()}).partial().nullish()});
const schema=z.object({pairs:z.array(pair).nullish()});
const emptyPeriod:MarketPeriod={priceChange:null,volume:null,buys:null,sells:null};
export function normalizeDexScreener(payload:unknown,mint:string):MarketMetrics|null{const parsed=schema.parse(payload);const pairs=(parsed.pairs??[]).filter(p=>p.chainId==="solana"&&(p.baseToken.address===mint||p.quoteToken.address===mint));if(!pairs.length)return null;pairs.sort((a,b)=>(b.liquidity?.usd??0)-(a.liquidity?.usd??0));const total=pairs.reduce((n,p)=>n+(p.liquidity?.usd??0),0);const lead=pairs[0];const periods=(['m5','h1','h6','h24'] as const).reduce((all,key)=>({...all,[key]:{...emptyPeriod,priceChange:lead.priceChange?.[key]??null,volume:lead.volume?.[key]??null,buys:lead.txns?.[key]?.buys??null,sells:lead.txns?.[key]?.sells??null}}),{} as MarketMetrics['periods']);const pools:PoolAnalysis[]=pairs.map(p=>{const liq=p.liquidity?.usd??null;const vol=p.volume?.h24??null;return{address:p.pairAddress,dex:p.dexId,pair:`${p.baseToken.symbol}/${p.quoteToken.symbol}`,liquidityUsd:liq,liquidityShare:liq!=null&&total>0?liq/total*100:null,createdAt:p.pairCreatedAt?new Date(p.pairCreatedAt).toISOString():null,volume24h:vol,volumeLiquidityRatio:vol!=null&&liq?vol/liq:null}});return{priceUsd:lead.priceUsd,priceSol:lead.quoteToken.symbol==="SOL"?lead.priceNative:null,liquidityUsd:total||null,fdv:lead.fdv,marketCap:lead.marketCap,periods,pools}}
export async function getMarketData(mint:string){const response=await fetchWithPolicy(`https://api.dexscreener.com/token-pairs/v1/solana/${encodeURIComponent(mint)}`,{headers:{Accept:"application/json"}});const pairs=await response.json();return normalizeDexScreener({pairs},mint)}
