import { Connection,PublicKey } from "@solana/web3.js";
import { ExtensionType,getDefaultAccountState,getExtensionTypes,getMint,getMintCloseAuthority,getPermanentDelegate,getTransferFeeConfig,getTransferHook,TOKEN_2022_PROGRAM_ID,TOKEN_PROGRAM_ID } from "@solana/spl-token";
import type { HolderAnalysis,TokenAuthorities,TokenExtensionAnalysis,TokenIdentity } from "@/lib/types";
const RPC=process.env.SOLANA_RPC_URL?.trim()||"https://api.mainnet-beta.solana.com";
export const connection=new Connection(RPC,{commitment:"confirmed",confirmTransactionInitialTimeout:8_000});
const explanations:Record<string,string>={TransferFeeConfig:"Transfers können eine programmierte Gebühr einbehalten.",PermanentDelegate:"Ein permanenter Delegate kann je nach Konfiguration Transfers oder Burns für Token-Konten autorisieren.",TransferHook:"Transfers führen zusätzliche Programmlogik aus; deren Sicherheit wurde hier nicht vollständig geprüft.",DefaultAccountState:"Neue Token-Konten können standardmäßig eingefroren sein.",NonTransferable:"Der Token ist als nicht übertragbar konfiguriert.",MintCloseAuthority:"Eine Authority kann den Mint unter den Programmregeln schließen.",Pausable:"Token-Aktivitäten können pausierbar sein."};
const riskFor=(name:string):TokenExtensionAnalysis['risk']=>name==="PermanentDelegate"||name==="NonTransferable"?"critical":name==="TransferFeeConfig"||name==="TransferHook"||name==="DefaultAccountState"||name==="Pausable"?"warning":"info";
export async function getOnChainToken(key:PublicKey):Promise<{token:TokenIdentity;authorities:TokenAuthorities;extensions:TokenExtensionAnalysis[];holders:HolderAnalysis|null}>{
 const account=await connection.getAccountInfo(key); if(!account||(!account.owner.equals(TOKEN_PROGRAM_ID)&&!account.owner.equals(TOKEN_2022_PROGRAM_ID)))throw new Error("UNSUPPORTED_MINT");
 const program=account.owner; const mint=await getMint(connection,key,"confirmed",program); const is2022=program.equals(TOKEN_2022_PROGRAM_ID);
 const token:TokenIdentity={name:null,symbol:null,mint:key.toBase58(),program:is2022?"Token-2022":"SPL Token",isToken2022:is2022,supply:mint.supply.toString(),decimals:mint.decimals,logoUrl:null};
 const authorities:TokenAuthorities={mintAuthority:mint.mintAuthority?.toBase58()??null,mintRevoked:mint.mintAuthority===null,freezeAuthority:mint.freezeAuthority?.toBase58()??null,freezeRevoked:mint.freezeAuthority===null};
 const extensions:TokenExtensionAnalysis[]=is2022?getExtensionTypes(mint.tlvData).map(type=>{const name=ExtensionType[type]??`Extension ${type}`;let authority:string|null=null;const configuration:Record<string,string|number|boolean|null>={};try{if(type===ExtensionType.PermanentDelegate)authority=getPermanentDelegate(mint)?.delegate.toBase58()??null;if(type===ExtensionType.TransferHook){const value=getTransferHook(mint);authority=value?.authority?.toBase58()??null;configuration.programId=value?.programId.toBase58()??null}if(type===ExtensionType.MintCloseAuthority)authority=getMintCloseAuthority(mint)?.closeAuthority.toBase58()??null;if(type===ExtensionType.DefaultAccountState)configuration.state=String(getDefaultAccountState(mint)?.state??"unknown");if(type===ExtensionType.TransferFeeConfig){const value=getTransferFeeConfig(mint);authority=value?.transferFeeConfigAuthority?.toBase58()??null;configuration.withdrawAuthority=value?.withdrawWithheldAuthority?.toBase58()??null;configuration.newerFeeBasisPoints=value?.newerTransferFee.transferFeeBasisPoints??null;configuration.maximumFee=value?.newerTransferFee.maximumFee.toString()??null}}catch{configuration.details="Konfiguration konnte nicht vollständig dekodiert werden"}return{type:name,explanation:explanations[name]??"Zusätzliche Token-2022-Mint-Erweiterung erkannt.",authority,configuration,risk:riskFor(name)}}):[];
 let holders:HolderAnalysis|null=null;try{const largest=await connection.getTokenLargestAccounts(key,"confirmed");const supply=Number(mint.supply);const raw=largest.value.slice(0,20).map(item=>({address:item.address.toBase58(),owner:null,amount:item.amount,percentage:supply>0?Number(item.amount)/supply*100:0,classification:null,classificationConfidence:null}));const sum=(n:number)=>raw.slice(0,n).reduce((v,h)=>v+h.percentage,0);holders={raw,adjusted:raw,top1:sum(1),top5:sum(5),top10:sum(10),top20:sum(20),note:"Adjusted entspricht derzeit RAW: Es wurde keine Adresse ohne ausreichend sichere Klassifikation ausgeschlossen."}}catch{holders=null}
 return{token,authorities,extensions,holders};
}
