import { RISK_CONFIG as C } from "./risk-config"; import type { Evidence,HolderAnalysis,MarketMetrics,RiskAssessment,RiskFinding,TokenAuthorities,TokenExtensionAnalysis } from "@/lib/types";
const rpc:Evidence[]=[{source:"solana_rpc",detail:"Direkt aus dem Mint-Konto gelesen"}], marketEvidence:Evidence[]=[{source:"market_provider",detail:"DexScreener-Pooldaten"}];
export function assessRisk(input:{authorities:TokenAuthorities;extensions:TokenExtensionAnalysis[];holders:HolderAnalysis|null;market:MarketMetrics|null;creatorAvailable:boolean;routeAvailable:boolean}):RiskAssessment{
 const f:RiskFinding[]=[];const add=(x:RiskFinding)=>f.push(x);const authority=(kind:"mint"|"freeze",active:boolean)=>add({id:`${kind}-authority`,title:`${kind==="mint"?"Mint":"Freeze"} Authority ${active?"aktiv":"widerrufen"}`,category:"CONTROL",weight:kind==="mint"?C.weights.mintAuthority:C.weights.freezeAuthority,status:active?"warning":"ok",measuredValue:active?"aktiv":"revoked",explanation:active?(kind==="mint"?"Eine aktive Mint Authority kann – abhängig von der Token-Konfiguration – weitere Token erzeugen.":"Eine aktive Freeze Authority kann bestimmte Token-Konten einfrieren."):"Dieser konkrete Authority-Check war unauffällig; das ist keine Sicherheitsgarantie.",evidence:rpc,dataAvailable:true});authority("mint",!input.authorities.mintRevoked);authority("freeze",!input.authorities.freezeRevoked);
 const holder=(id:string,title:string,value:number|null,limit:number,weight:number)=>add({id,title,category:"HOLDERS",weight,status:value==null?"unknown":value>=limit?"warning":"ok",measuredValue:value==null?null:`${value.toFixed(1)} %`,explanation:value==null?"Holderdaten fehlen.":value>=limit?"Die gemessene Konzentration überschreitet den dokumentierten heuristischen Schwellenwert.":"Dieser Konzentrationscheck war unauffällig.",evidence:value==null?[]:rpc,dataAvailable:value!=null});holder("top1","Top-1-Konzentration",input.holders?.top1??null,C.thresholds.top1,C.weights.top1);holder("top10","Top-10-Konzentration",input.holders?.top10??null,C.thresholds.top10,C.weights.top10);
 const liq=input.market?.liquidityUsd??null;add({id:"liquidity",title:"Erkannte Liquidität",category:"LIQUIDITY",weight:C.weights.liquidity,status:liq==null?"unknown":liq<C.thresholds.liquidityCritical?"critical":liq<C.thresholds.liquidityLow?"warning":"ok",measuredValue:liq==null?null:`$${liq.toFixed(0)}`,explanation:liq==null?"Marktdaten nicht verfügbar.":"Niedrige Liquidität kann Handel und Preisauswirkung verschärfen.",evidence:liq==null?[]:marketEvidence,dataAvailable:liq!=null});
 for(const ext of input.extensions){const weight=ext.type==="PermanentDelegate"?C.weights.permanentDelegate:ext.type==="TransferHook"?C.weights.transferHook:ext.type==="TransferFeeConfig"?C.weights.transferFee:ext.type==="DefaultAccountState"?C.weights.defaultFrozen:ext.type==="NonTransferable"?C.weights.nonTransferable:3;add({id:`extension-${ext.type}`,title:ext.type,category:"TOKEN_MECHANICS",weight,status:ext.risk==="critical"?"critical":ext.risk==="warning"?"warning":"ok",measuredValue:ext.authority,explanation:ext.explanation,evidence:rpc,dataAvailable:true})}
 const change=input.market?.periods.h1.priceChange??null;add({id:"market-move",title:"Kurzfristige Preisbewegung",category:"MARKET",weight:C.weights.marketMove,status:change==null?"unknown":Math.abs(change)>C.thresholds.marketMove?"warning":"ok",measuredValue:change==null?null:`${change.toFixed(1)} %`,explanation:"Preisbewegung ist nur ein begrenzt gewichteter Marktindikator und kein Betrugsnachweis.",evidence:change==null?[]:marketEvidence,dataAvailable:change!=null});
 add({id:"creator",title:"Vermuteter Ersteller",category:"CREATOR_BEHAVIOR",weight:C.weights.creator,status:"unknown",measuredValue:null,explanation:"Ersteller konnte ohne ausreichend belastbare Transaktions-Evidenz nicht zuverlässig bestimmt werden.",evidence:[],dataAvailable:input.creatorAvailable});
 const available=f.filter(x=>x.dataAvailable);const max=available.reduce((n,x)=>n+x.weight,0);const points=available.reduce((n,x)=>n+(x.status==="critical"?x.weight:x.status==="warning"?x.weight*.65:0),0);const score=max?Math.round(points/max*100):0;const coverage=C.coverage.onChain+(input.holders?C.coverage.holders:0)+(input.market?C.coverage.market:0)+(input.creatorAvailable?C.coverage.creator:0)+(input.routeAvailable?C.coverage.routeability:0);const order={critical:0,warning:1,ok:2,unknown:3};return{score,category:C.bands.find(b=>score<=b.max)?.label??C.bands.at(-1)!.label,coverage,confidence:coverage>=85?"hoch":coverage>=60?"mittel":"niedrig",reliable:coverage>=C.minimumReliableCoverage,findings:f.sort((a,b)=>order[a.status]-order[b.status])};
}
